version = 0.1

[default.deploy.parameters]
stack_name = "codebreakercontest07"
resolve_s3 = true
s3_prefix = "codebreakercontest07"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "JudgeName=\"codebreakercontest07\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
