AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Step Functions state machines for Codebreaker grading workflow

Parameters:
  JudgeName:
    Type: String
  GraderProblemInitFunctionArn:
    Type: String
  TestcaseGraderWrapperFunctionArn:
    Type: String
  GraderProblemScorerFunctionArn:
    Type: String
  WebSocketInvokeFunctionArn:
    Type: String

Resources:
  GradingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${JudgeName}-grading
      DefinitionUri: ../state-machines/grading.asl.json
      DefinitionSubstitutions:
        ProblemInitFunctionArn: !Ref GraderProblemInitFunctionArn
        TestcaseGraderWrapperFunctionArn: !Ref TestcaseGraderWrapperFunctionArn
        ProblemScorerFunctionArn: !Ref GraderProblemScorerFunctionArn
        JudgeName: !Ref JudgeName
      Type: STANDARD
      Policies:
        - AWSLambdaRole

  WebSocketStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${JudgeName}-websocket
      DefinitionUri: ../state-machines/websocket.asl.json
      DefinitionSubstitutions:
        WebSocketInvokeFunctionArn: !Ref WebSocketInvokeFunctionArn
      Type: EXPRESS
      Policies:
        - AWSLambdaRole
